# Numpy

## Installation et import

Installer numpy via le gestionnaire de dependance pip grace a la commande :

pip install numpy

Import de numpy dans un fichier

In [2]:
import numpy as np

## Description

Numpy est une libraire optimisee pour le calcul mathematique

## Utilisation

Creation d'objets

In [4]:
np.array([0, 1, 3])

array([0, 1, 3])

In [5]:
np.array([[0, 1, 3], [0, 1, 3]])

array([[0, 1, 3],
       [0, 1, 3]])

In [6]:
np.arange(3 * 4 * 5).reshape(3, 4, 5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [8]:
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

Obtention de la shape d'un array

In [9]:
np.eye(5).shape

(5, 5)

In [10]:
np.arange(4).shape

(4,)

Ajout d une valeur a tous les elements

In [11]:
np.zeros((5,5)) + 1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

Somme terme a terme

In [12]:
np.eye(5) + np.arange(5*5).reshape(5, 5)

array([[ 1.,  1.,  2.,  3.,  4.],
       [ 5.,  7.,  7.,  8.,  9.],
       [10., 11., 13., 13., 14.],
       [15., 16., 17., 19., 19.],
       [20., 21., 22., 23., 25.]])

Multiplication terme a terme

In [13]:
np.eye(5) + np.arange(5*5).reshape(5, 5)

array([[ 1.,  1.,  2.,  3.,  4.],
       [ 5.,  7.,  7.,  8.,  9.],
       [10., 11., 13., 13., 14.],
       [15., 16., 17., 19., 19.],
       [20., 21., 22., 23., 25.]])

Multiplication matricielle

In [14]:
np.dot(np.eye(5), np.arange(5*5).reshape(5, 5))

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.,  9.],
       [10., 11., 12., 13., 14.],
       [15., 16., 17., 18., 19.],
       [20., 21., 22., 23., 24.]])

Obtention d'elements (idem que pour les listes pour chaque elements)

In [15]:
arr = np.arange(2*3*4).reshape(2, 3, 4)

In [16]:
arr[:,1:-1,0]

array([[ 4],
       [16]])

## Algebre lineaire

numpy possede un package d'algebre lineaire np.linalg. Exemple d utilisation avec la fonction inv qui inverse une matrice

In [17]:
np.linalg.inv(np.arange(4).reshape((2,2)))

array([[-1.5,  0.5],
       [ 1. ,  0. ]])